In [1]:
import numpy
import pandas
import matplotlib.pyplot
import seaborn
from sklearn.model_selection import train_test_split

In [2]:
import numpy as np
# ndarray 넘파이의 기반 데이터 타입

In [7]:
array1=np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:', array1.shape)         # 1차원[]일 때는 열의 갯수만 표시 

array2=np.array([[1,2,3],
                 [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:', array2.shape)         # 2차원 (r,c)

array3=np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:', array3.shape)        # 2차원 [[]]


# 3차원일때는 (2,2,2) 형태 

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [6]:
print(f'array1:{array1.ndim}차원')   # 다른 방식 

array1:1차원


In [5]:
## 차수 확인
print('array1:{: 0}차원,  array2:{: 1}차원,  array3:{:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1: 1차원,  array2: 2차원,  array3: 2차원


In [16]:
## 데이터 타입
# 리스트: 서로 다른 데이터 타입 가질수 있다.  ndarray: 항상 같은 데이터 타입만 
list1= [1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype)

list2=[1,2,'test']
array2 = np.array(list2)
print(array2,array2.dtype)            # int < 문자 

list3=[1,2,3.0]
array3 =np.array(list3)
print(array3,array3.dtype)          # int < float


<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32
['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [19]:
# 데이터 타입 변경 --> astype()    목적: 메모리 절약 
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)           # int -->float

array_int1 = array_float.astype('int32')
print(array_int1,array_int1.dtype)             # float --> int

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)                 

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [24]:
## ndarray 생성 - 테스트용 데이터를 만들거나 대규모 데이터를 일괄적으로 초기화하기 위해 사용
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype,sequence_array.shape)

zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [40]:
## reshape - 차원 크기 변경
array1 = np.arange(10)
print('array1:\n',array1)

array2=array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

# array1.reshape(4,3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [46]:
# -1 사용
array1 = np.arange(20)
print(array1)
array2 = array1.reshape(-1,4)          # 고정된 4개의 열(column)에 맞게 shape 변환
print('array2 shape:',array2.shape)
array3 = array1.reshape(4,-1)         # 고정된 4개의 행(row)에 맞게 shape 변환
print('array3 shape:',array3.shape)

# array4 = array1.reshape(-1,3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
array2 shape: (5, 4)
array3 shape: (4, 5)


In [54]:
array1 = np.arange(8)
print('array1:\n',array1.tolist())
array3d = array1.reshape(((2,2,2)))
print('array3d:\n',array3d.tolist())

# 3차원 ndarray 를 2차원 ndarray로 변환
array5 =array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray 를 2차원 ndarray 로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:', array5.shape)

array1:
 [0, 1, 2, 3, 4, 5, 6, 7]
array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [68]:
### 데이터 추출
### 인덱싱 - 일부 데이터 세트나 특정 데이터만을 선택 가능

# 단일 인덱싱

# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop= 10)
print('array1:', array1)
# index 는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

print('맨 뒤의 값:', array1[-1],'맨 뒤에서 두번째 값:', array1[-2])

# 데이터 수정
array1[0] =9
array1[8] =0
print('array1:', array1)

# 다차원 ndarray (feat. 2차원)
array1d = np.arange(start=1, stop= 10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:',array2d[0,0])
print('(row=0, col=1) index 가리키는 값:',array2d[0,1])
print('(row=1, col=0) index 가리키는 값:',array2d[1,0])
print('(row=2, col=2) index 가리키는 값:',array2d[2,2])
# axis=0 행(default) , axis=1 열 


array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>
맨 뒤의 값: 9 맨 뒤에서 두번째 값: 8
array1: [9 2 3 4 5 6 7 8 0]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [81]:
##슬라이싱 
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

# 다차원 
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2,0:2]\n', array2d[0:2,0:2])
print('array2d[1:3,0:3]\n', array2d[1:3,0:3])
print('array2d[1:3,:]\n',array2d[1:3,:])
print('array2d[:,:]\n',array2d[:,:])
print('array2d[:2,1:]\n',array2d[:2,1:])
print('array2d[:2,0]\n',array2d[:2,0])

print('-------------')

print(array2d[0])
print(array2d[1])
print('array2d[0] shape:',array2d[0].shape,'array2d[1] shape:',array2d[1].shape)

[1 2 3]
<class 'numpy.ndarray'>
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2,0]
 [1 4]
-------------
[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [4]:
## 펜시 인덱싱: 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2] =>', array3.tolist())         # (0,2),(1,2)--> [3,6]

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2] =>', array4.tolist())      # ((0,0),(0,1)),((1,0),(1,1))-->[[1,2],[4,5]]

array5 =array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())         # ((0,:),(1,:)) --> [[1,2,3],[4,5,6]]



[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0,1],2] => [3, 6]
array2d[[0,1],0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


In [12]:
## 불린 인덱싱: 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True 에 해당하는 인덱스 위치에 있는 
                # 데이터의 ndarray를 반환 
    
array1d = np.arange(start=1, stop=10)
#  [] 안에 array1d > 5 Boolean indexing 을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)


boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])   # array1d > 5
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]
불린 인덱스로 필터링 결과: [6 7 8 9]
일반 인덱스로 필터링 결과: [6 7 8 9]


In [14]:
## 행렬의 정렬
org_array = np.array([3,1,9,5])
print('원본 행렬:',org_array)
# np.sort() 로 정렬:  원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
sort_array1 = np.sort(org_array)

print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

# ndarray.sort()로 정렬 : 원 행렬 자체를 정렬한 형태로 변환하며 반환값은 none
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬 :', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

# 내림차순
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬 : None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]
내림차순으로 정렬: [9 5 3 1]


In [20]:
# 2차원 행렬의 정렬 
array2d =np.array([[8,12],[7,1]])
print(array2d)

sort_array2d_axis0 = np.sort(array2d, axis = 0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)    # 세로 정렬

sort_array2d_axis1 = np.sort(array2d, axis = 1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)   # 가로 정렬 

[[ 8 12]
 [ 7  1]]
로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [24]:
# 정렬된 행렬의 인덱스 반환 np.argsort()  ## 중요 
org_array= np.array([3,1,9,5])
sort_indices= np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

# 내림차순
sort_indices_desc = np.argsort(org_array)[::-1]      #([9,5,3,1])
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [25]:
# 행렬 내적  dot()
A = np.array( [[1,2,3],[4,5,6]])
B= np.array([[7,8],[9,10],[11,12]])
dot_product = np. dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [26]:
# 전치 행렬  transpose()
A = np.array([[1,2],[3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
